language: ruby
rvm:
- 2.2.2
notifications:
  email: false
  slack:
    secure: GZdf4YAEI9uEly5FBAeYGl6grQi9YgtXImTCWBsrtSyqcVu19paorOe0zVIaXuQttv+8wNHcRx67U9Af/Mu3xWhLcNII4ukE9mKIvJm2TvQBbGpfv1slQ8K9QTTDrQZ4iH8X2ixt3FRseRywb/R4ANsqLbJn4hp/W81i8RG92kTREmR0oTT5Uya5eD2sb0iPOs9qy7gIxAdxIffUTmFiTlEo0R/BAiQFfpjGefbzYaMgi0fpTKvda8PN09itFuV2qNcFHClQHnFpuk3vpKO0WqQz0mfk453xPDihQXS0gneVvtIoqUJYuFy7RGep2fqlIccQV8U61HsVKSuEC3HIRXCdwJDpypOuxNXFuTmT0H6mfL05akUPGseG3S3Q4uTYeqYMjLOR+cDbNFJzsILDmJ0xCDvMnicoghFkB/eBpE9T5+VWiukI2KYo7comf+NTBKLAijxI8jrgZH5PjBcaotD4WQCqBZyEUs2wqWr8Xbup3hRsRzD3pG5PIlhy6LK/l7iXcJ/A2U2yI2ciKnU6Xqb/LjSAxOHwUimloKxwCvluRzVBbLHC21rKOIGT0wokXszpmhlRw2MDx1+9zssKMSS+REct1Ow+pFqCpVvPhV5mLdOjILcA3qeucFqH484SH8/GdfYTGYqSKmgLbTZezmEsnkDe9PmIxh3O7DKDIUY=
