require 'logger'
require 'aws-sdk-core'
require 'active_support/notifications'
require './lib/stream_reader/sequence_number_tracker'
require './lib/stream_reader/avro_parser'
require './lib/stream_reader/version'
